In [5]:
import pandas as pd
import numpy as np
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
from selenium.webdriver.common.keys import Keys

#### Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.

In [21]:
driver=webdriver.Chrome()
url='https://www.naukri.com/'
driver.get(url)
time.sleep(2)
searchJob=driver.find_element_by_id('qsb-keyword-sugg')
time.sleep(2)
searchJob.send_keys('Data Analyst')
searchJoblocation=driver.find_element_by_id('qsb-location-sugg')
searchJoblocation.send_keys('Bangalore')
time.sleep(2)
search=driver.find_element_by_class_name('search-btn')
search.click()
time.sleep(2)
jobtitle=[]
otherdetail=[]

job_titles=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for title in job_titles:
    jobtitle.append(title.text)
    
otherdetails=driver.find_elements_by_xpath('//span [@class="ellipsis fleft fs12 lh16"]')
for details in otherdetails:
    otherdetail.append(details.text)
    

experiance=otherdetail[0::3]
location=otherdetail[2::3]

company_name=[]
companyname=driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]')
for i in companyname:
    company_name.append(i.text)
    
df=pd.DataFrame()
df['Job title']=jobtitle
df['Location']=location
df['Experiance']=experiance
df['Company Name']=company_name

df

,Job title,Location,Experiance,Company Name
0,Data Scientist / Data Analyst -Business Analyst,"Hyderabad/Secunderabad, Chennai, Bangalore/Ben...",0-3 Yrs,Inflexion Analytix Private Limited
1,Consultant - Data Analyst,Bangalore/Bengaluru,0-2 Yrs,Flipkart Internet Private Limited
2,Assistant Vice President - MIS & Reporting ( B...,"Mumbai, Bangalore/Bengaluru",10-15 Yrs,INTERTRUSTVITEOS CORPORATE AND FUND SERVICES P...
3,Network Design & Data Analyst,Bangalore/Bengaluru,0-2 Yrs,Dell International Services India Private Limited
4,Business Data Analyst - MIS & Reporting,"Mumbai, Bangalore/Bengaluru",3-8 Yrs,INTERTRUST GROUP
5,Excel VBA Jobs Bangalore | VBA data analyst Jobs,"Coimbatore, Bangalore/Bengaluru, Trivandrum/Th...",0-2 Yrs,Mind Circus Innovation
6,Software Developer / Web Developer/data analyst,"Hyderabad/Secunderabad, Bangalore/Bengaluru",0-1 Yrs,Edubridgeindia
7,"Data Analyst – Financial, Healthcare, Sports B...","Pune, Chennai, Bangalore/Bengaluru",2-4 Yrs,Quantsys
8,FTE - Regional BI - Functional Data Analyst,"Davangere, Bangalore/Bengaluru",5-8 Yrs,Schneider Electric India Pvt. Ltd.
9,Deputy Manager - Data Analyst,"Davangere, Bangalore/Bengaluru",3-6 Yrs,Schneider Electric India Pvt. Ltd.
10,Data Analyst,Bangalore/Bengaluru,8-13 Yrs,Allegis Services India Pvt. Ltd.
11,Senior Security Specialist - CS Awareness & Da...,Bangalore/Bengaluru,4-7 Yrs,Cognizant Technology Solutions India Pvt Ltd
12,Data Analyst,Bangalore/Bengaluru,0-5 Yrs,Siemens Limited
13,Data Analyst,Bangalore/Bengaluru,0-2 Yrs,Bright Money
14,Senior Data Analyst,Bangalore/Bengaluru(2nd Phase JP Nagar),5-8 Yrs,"Liventus, Inc."
15,Data Analyst - Consumer Experience,Bangalore/Bengaluru,5-10 Yrs,ExecBoardinAsia
16,Consultant-Data Analyst -Bangalore,Bangalore/Bengaluru,2-3 Yrs,Innovsource Services Private Limited
17,Hiring For Freshers - Data Analyst/Business An...,Bangalore/Bengaluru,0-0 Yrs,Nevvit Technologies
18,Data Analyst CX,Bangalore/Bengaluru,6-10 Yrs,Philips India Limited
19,Senior Data Analyst,Bangalore/Bengaluru,4-5 Yrs,Flipkart Internet Private Limited

### Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, full job-description. You have to scrape first 10 jobs data.

In [22]:
driver=webdriver.Chrome()
url='https://www.naukri.com/'
driver.get(url)
time.sleep(2)
searchJob=driver.find_element_by_id('qsb-keyword-sugg')
time.sleep(2)
searchJob.send_keys('Data Analyst')
searchJoblocation=driver.find_element_by_id('qsb-location-sugg')
searchJoblocation.send_keys('Bangalore')
time.sleep(2)
search=driver.find_element_by_class_name('search-btn')
search.click()
time.sleep(2)
jobtitle=[]
otherdetail=[]

job_titles=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for title in job_titles:
    jobtitle.append(title.text)
    
otherdetails=driver.find_elements_by_xpath('//span [@class="ellipsis fleft fs12 lh16"]')
for details in otherdetails:
    otherdetail.append(details.text)
    
location=otherdetail[2::3]

company_name=[]
companyname=driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]')
for i in companyname:
    company_name.append(i.text)
    
urls=[]
for url in driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]'):
    urls.append(url.get_attribute('href'))
    
descriptions=[]
for link in urls[:10]:
    driver.get(link)
    time.sleep(3)
    #fetching job description
    try:
        description=driver.find_element_by_xpath('//div[@class="dang-inner-html"]')
        descriptions.append(description.text.replace('\n',''))
    except NoSuchElementException:
        descriptions.append('No Job description Available')
        
df2=pd.DataFrame()
df2['Job title']=jobtitle[:10]
df2['Location']=location[:10]
df2['Company']=company_name[:10]
df2['Job description']=descriptions

df2

,Job title,Location,Company,Job description
0,Data Analyst (SQL) Bangalore,Bangalore/Bengaluru,Talent Corner HR Services Pvt Ltd,Excellent in SQL Transaction languageUse VBA m...
1,Marketing Technology Data Analyst,Bangalore/Bengaluru,WeGo,"As part of the Marketing Technology Team, the ..."
2,Data Analyst - Quant & Data Mining,Bangalore/Bengaluru,Catalyst,Responsibilities :- Apply your expertise in qu...
3,Data Analyst ( Leading MNC ),Bangalore/Bengaluru,BRAINHUNT CONSULTANTS PRIVATE LIMITED,Strong data manipulation skills and the abilit...
4,Process Data Analyst,Bangalore/Bengaluru,Hitachi ABB Power Grids,Analyze customer feedback data on various IT r...
5,Data Analyst,Bangalore/Bengaluru,Radial HR Solutions,- You must have 2 to 4 years of experience in ...
6,Technical Data Analyst - Progton Technologies,Bangalore/Bengaluru,Progton Technologies LLP,Roles and responsibilities:Candidates should b...
7,Data Analyst,Bangalore/Bengaluru,PharmEasy,ResponsibilitiesA Data Analyst would be respon...
8,Data Analyst II - Customer Support,Bangalore/Bengaluru,VIMEO TECHNOLOGIES PRIVATE LIMITED,The Insights Analytics Specialist will shape t...
9,Data Analyst (Remote),Bangalore/Bengaluru,ICF Consulting,We are looking for a talented Junior Data Anal...

### In this question you have to scrape data using the filters.
You have to use the location and salary filter.
You have to scrape data for “Data Scientist” designation for first 10 job results.
You have to scrape the job-title, job-location, company_name,
experience_required.
The location filter to be used is “Delhi/NCR”
The salary filter to be used is “3-6” lakhs
The task will be done as shown in the below steps:
1. first get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill,Designations,Companies” field .
3. Then click the search button.
4. Then apply the location filter and salary filter by checking the respective boxes
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.
Note- All of the above steps have to be done in code. No step is to be done
manually.

In [23]:
driver=webdriver.Chrome()
url='https://www.naukri.com/'
driver.get(url)
time.sleep(2)

searchJob=driver.find_element_by_id('qsb-keyword-sugg')
time.sleep(2)

searchJob.send_keys('Data Scientist')
search=driver.find_element_by_class_name('search-btn')
search.click()
time.sleep(2)

locationfilter=driver.find_element_by_xpath('//span[@title="Delhi / NCR"]')
locationfilter.click()
time.sleep(2)

salaryfilter=driver.find_element_by_xpath('//span[@title="3-6 Lakhs"]')
salaryfilter.click()
time.sleep(2)

jobtitle=[]
job_titles=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for title in job_titles:
    jobtitle.append(title.text)

otherdetail=[]
otherdetails=driver.find_elements_by_xpath('//span [@class="ellipsis fleft fs12 lh16"]')
for details in otherdetails:
    otherdetail.append(details.text)
location=otherdetail[2::3]
experiance=otherdetail[0::3]

company_name=[]
companyname=driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]')
for i in companyname:
    company_name.append(i.text)

df3=pd.DataFrame()
df3['Job titel']=jobtitle[:10]
df3['Location']=location[:10]
df3['Experiance']=experiance[:10]
df3['Company name']=company_name[:10]

df3

,Job titel,Location,Experiance,Company name
0,Data Scientist/Data Analyst /Business Analyst,"Pune, Delhi / NCR, Mumbai (All Areas)",0-3 Yrs,Inflexion Analytix Private Limited
1,Only Fresher / Data Scientist / Data Analyst /...,"Noida, Greater Noida, Delhi / NCR",0-0 Yrs,GABA Consultancy services
2,Advanced Analytics -Data Scientist,"New Delhi, Hyderabad/Secunderabad",3-7 Yrs,ERM Placement Services (P) Ltd.
3,Data Scientist (Early Joiner),Noida(Sector-59 Noida),4-8 Yrs,R Systems International Ltd.
4,Data Scientist - Machine Learning/ NLP,Gurgaon/Gurugram,2-6 Yrs,TalPro
5,Data Scientist || Python || C2H,"Noida, Kolkata, Gurgaon/Gurugram, Bangalore/Be...",4-6 Yrs,Growel Softech Pvt. Ltd.
6,Data Scientist || Python || C2H,"Noida, Kolkata, Gurgaon/Gurugram, Bangalore/Be...",4-6 Yrs,Growel Softech Pvt. Ltd.
7,Chaayos is Looking For Data Scientist,New Delhi,0-5 Yrs,Chaayos (Sunshine Teahouse Pvt. Ltd.)
8,Data Scientist,"Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru",3-7 Yrs,Fractal Analytics
9,Data Scientist (Time Series),"Noida, New Delhi, Gurgaon/Gurugram, Delhi / NCR",3-6 Yrs,TALENT INTEGRATORS

### Scrape data of first 100 sunglasses listings on flipkart.com. 
You have to scrape four attributes:
1. Brand
2. Product Description
3. Price
4. Discount %

In [22]:
driver=webdriver.Chrome()
url="https://www.flipkart.com/"
driver.get(url)
time.sleep(2)

search=driver.find_element_by_xpath('//input[@type="text"]')
search.send_keys('Sunglasses')
time.sleep(2)
searchicon=driver.find_element_by_xpath('//button[@type="submit"]')
searchicon.click()
time.sleep(2)

urls=[]
for url in driver.find_elements_by_xpath('//a[@class="IRpwTa"]'):
    urls.append(url.get_attribute('href'))
brands=[]
productdescriptions=[]
prices=[]
discounts=[]

for urls_ in urls:
    driver.get(urls_)
    # fetch product brand
    brand=driver.find_elements_by_xpath('//span[@class="G6XhRU"]')
    for b in brand:
        brands.append(b.text)
    # product description 
    productdescription= driver.find_elements_by_xpath('//span[@class="B_NuCI"]')
    for pd in productdescription:
        productdescriptions.append(pd.text)
        
    # price
    price=driver.find_elements_by_xpath('//div[@class="_30jeq3 _16Jk6d"]')
    for p in price:
        prices.append(p.text)
        
    # discounts
    discount=driver.find_elements_by_xpath('//div[@class="_3Ay6Sb _31Dcoz pZkvcx"]/span')
    for d in discount:
        discounts.append(d.text)

import pandas as pd        
sunglasses=pd.DataFrame()
sunglasses['Brand']=brands
sunglasses['Product Description']=productdescriptions
sunglasses['Price']=prices
sunglasses['Discount']=discounts

sunglasses

,Brand,Product Description,Price,Discount
0,PIRASO,UV Protection Aviator Sunglasses (54) (For Me...,₹237,85% off
1,ROYAL SON,"Polarized, UV Protection Round Sunglasses (49)...",₹664,66% off
2,kingsunglasses,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹299,88% off
3,Fastrack,UV Protection Wayfarer Sunglasses (Free Size) ...,₹758,15% off
4,Fastrack,UV Protection Rectangular Sunglasses (Free Siz...,₹513,35% off
5,PIRASO,UV Protection Aviator Sunglasses (54) (For Me...,₹237,85% off
6,kingsunglasses,UV Protection Round Sunglasses (Free Size) (F...,₹349,78% off
7,PIRASO,UV Protection Wayfarer Sunglasses (32) (For M...,₹237,85% off
8,GANSTA,UV Protection Aviator Sunglasses (57) (For Me...,₹281,85% off
9,PHENOMENAL,UV Protection Retro Square Sunglasses (Free Si...,₹399,80% off
10,PHENOMENAL,UV Protection Round Sunglasses (53) (For Men ...,₹309,86% off
11,AISLIN,"UV Protection, Gradient Butterfly, Retro Squar...",₹498,67% off
12,Fastrack,UV Protection Wayfarer Sunglasses (56) (For M...,₹655,27% off
13,Fastrack,"UV Protection, Polarized Wayfarer Sunglasses (...",₹612,31% off
14,kingsunglasses,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹299,88% off
15,ROYAL SON,"Polarized, UV Protection Round Sunglasses (53)...",₹664,66% off
16,Fastrack,UV Protection Wayfarer Sunglasses (Free Size) ...,₹647,28% off
17,kingsunglasses,UV Protection Round Sunglasses (54) (For Men ...,₹225,79% off
18,Fastrack,"Gradient, UV Protection Wayfarer Sunglasses (F...",₹509,36% off
19,ROYAL SON,"Mirrored Aviator Sunglasses (55) (For Men, Bl...",₹379,74% off
20,ROZZETTA CRAFT,UV Protection Retro Square Sunglasses (Free Si...,₹499,77% off
21,Fastrack,UV Protection Aviator Sunglasses (58) (For Me...,"₹1,010",22% off
22,Silver Kartz,UV Protection Wayfarer Sunglasses (Free Size) ...,₹259,82% off
23,Wrogn,Mirrored Wayfarer Sunglasses (51) (For Men & ...,₹663,73% off
24,kingsunglasses,UV Protection Rectangular Sunglasses (Free Siz...,₹210,83% off
25,Fastrack,UV Protection Aviator Sunglasses (58) (For Me...,"₹1,085",16% off
26,DEIXELS,"UV Protection Aviator, Wayfarer Sunglasses (Fr...",₹213,82% off
27,ROYAL SON,UV Protection Rectangular Sunglasses (Free Siz...,₹499,66% off
28,PIRASO,UV Protection Aviator Sunglasses (Free Size) ...,₹331,79% off
29,Fastrack,UV Protection Wrap-around Sunglasses (Free Siz...,₹522,41% off
30,NuVew,UV Protection Aviator Sunglasses (58) (For Me...,₹215,72% off
31,ROYAL SON,UV Protection Retro Square Sunglasses (88) (F...,₹599,70% off
32,PIRASO,UV Protection Aviator Sunglasses (58) (For Me...,₹331,87% off
33,hipe,"Mirrored, UV Protection, Gradient Round Sungla...",₹197,86% off
34,PHENOMENAL,"UV Protection, Mirrored Retro Square Sunglasse...",₹399,80% off
35,elegante,UV Protection Round Sunglasses (Free Size) (F...,₹399,80% off
36,kingsunglasses,UV Protection Rectangular Sunglasses (55) (Fo...,₹349,76% off
37,Fastrack,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹738,26% off
38,Fastrack,UV Protection Aviator Sunglasses (Free Size) ...,₹592,34% off
39,ROYAL SON,Polarized Retro Square Sunglasses (52) (For M...,₹599,60% off

Write a python program to scrape data for first 10 job results for Data scientist Designation in Noida location. You have to scrape company_name, No. of days ago when job was posted, Rating of the company.

In [24]:
driver=webdriver.Chrome()
time.sleep(5)

url='https://www.glassdoor.co.in/index.htm'
driver.get(url)
driver.maximize_window()
time.sleep(5)

In [25]:
jobsearch=driver.find_element_by_xpath('//input[@id="sc.keyword"]')
jobsearch.send_keys('Data Scientist')
time.sleep(2)

for i in range(12):
    driver.find_element_by_xpath("//div[@class='d-flex flex-row align-items-center']//div[3]//div[1]//input").send_keys(Keys.BACK_SPACE)
time.sleep(5)


joblocation=driver.find_element_by_xpath('//input[@id="sc.location"]')
joblocation.send_keys('Noida')
time.sleep(2)


search=driver.find_element_by_xpath('//button[@type="submit"]')
search.click()
time.sleep(2)


company=[]
cmp=driver.find_elements_by_xpath('//div[@class="d-flex justify-content-between align-items-start"]/a/span')
for cmp_ in cmp:
    company.append(cmp_.text)
time.sleep(3)
    
no_of_days_ago=[]
nda=driver.find_elements_by_xpath('//div[@class="d-flex justify-content-between css-1qtdns2"]')
for day in nda:
    no_of_days_ago.append(day.text.replace('\n',' '))
time.sleep(3)
    
ratings=[]
try:
    rating=driver.find_elements_by_xpath('//span[@class="css-19pjha7 e1cjmv6j1"]')
    for r in rating:
        ratings.append(r.text)
except NoSuchElementException:
    ratings.append('-')
time.sleep(5)


glassdoor=pd.DataFrame()
glassdoor['Company']=company[:10]
glassdoor['No of days ago']=no_of_days_ago[:10]
glassdoor['Ratings']=ratings[:10]

glassdoor

                                           Company      No of days ago Ratings
0                                       Salesforce  Actively Hiring 5d     4.5
1                                          Bechtel  Actively Hiring 2d     4.0
2                                         Ericsson                 17d     4.1
3                                    NatWest Group              New 2d     3.9
4                                            Crowe             HOT 10d     3.8
5  Siemens Technology and Services Private Limited             HOT 22d     4.1
6                                         MobiKwik                 25d     4.0
7                         Lantern Digital Services                  4d     3.5
8                                             Novo   HOT Easy Apply 8d     4.2
9                                  Priority Vendor              HOT 9d     3.7

Write a python program to scrape the salary data for Data Scientist designation
in Noida location.
You have to scrape Company name, Number of salaries, Average salary, Min
salary, Max Salary.
The above task will be, done in the below steps:
1. first get the webpage https://www.glassdoor.co.in/Salaries/index.htm
2. Enter “Data Scientist” in Job title field and “Noida” in location field.
3. Click the search button.
4. After that you will land on the page, You have to scrape whole data from this webpage
5. Scrape data for first 10 companies. Scrape the min salary, max salary, company name, Average salary and rating of the company.
6.Store the data in a dataframe.
Note that all of the above steps have to be done by coding only and not manually.

In [40]:
driver=webdriver.Chrome()
url='https://www.glassdoor.co.in/Salaries/index.htm'
driver.get(url)
time.sleep(2)

keywordsearch=driver.find_element_by_xpath('//input[@id="KeywordSearch"]')
keywordsearch.send_keys('Data Scientist')
time.sleep(2)

locationserach=driver.find_element_by_xpath('//input[@id="LocationSearch"]')
for i in range(12):
    locationserach.send_keys(Keys.BACK_SPACE)
locationserach.send_keys('Noida')
searchbutton=driver.find_element_by_xpath('//button[@id="HeroSearchButton"]')
searchbutton.click()
time.sleep(2)

signin=driver.find_element_by_xpath('//div[@class="center description py-xsm "]/a')
signin.click()
time.sleep(5)

email=driver.find_element_by_xpath('//input[@id="userEmail"]')
email.send_keys('itzs.nik@gmail.com')

password=driver.find_element_by_xpath('//input[@id="userPassword"]')
password.send_keys('Gd@97988')

login=driver.find_element_by_xpath('//button[@class="gd-ui-button minWidthBtn css-8i7bc2"]')
login.click()

# compnay=[]
# companyname=driver.find_elements_by_xpath('//a[@class="css-f3vw95 e1aj7ssy3"]')
# for cmp in companyname:
#     compnay.append(cmp.text)
# time.sleep(2)

# salaries=[]
# salary=driver.find_elements_by_xpath('//div[@class="d-flex mt-xxsm css-79elbk epuxyqn0"]/p/class="m-0 css-1vkj9it"')
# for sal in salary:
#     salaries.append(sal.text)
# salaries

# details=[]
# detail=driver.find_elements_by_xpath('//div[@class="py css-17435dd"]')
# for detail_ in detail:
#     details.append(detail_.text)
    
# detail_

Go to webpage https://www.amazon.in/. Enter “Laptop” in the search field and then click the search icon.
Then set CPU Type filter to “Intel Core i7” and “Intel Core i9”
After setting the filters scrape first 10 laptops data. You have to scrape 3 attributes
for each laptop:
1. title
2. Ratings
3. Price

In [41]:
amazondriver=webdriver.Chrome()
url='https://www.amazon.in/'
amazondriver.get(url)
time.sleep(2)

In [42]:
searchbox=amazondriver.find_element_by_xpath('//input[@id="twotabsearchtextbox"]')
searchbox.send_keys('laptop')

searchbutton=amazondriver.find_element_by_xpath('//input[@id="nav-search-submit-button"]')
searchbutton.click()

# filterbutton1=amazondriver.find_elements_by_class_name("Intel Core i7")
# filterbutton1.click()

filterurl=amazondriver.find_elements_by_xpath('//a[@class="a-link-normal s-navigation-item"]')

Go to the link - https://www.myntra.com/shoes. Set Price filter to “Rs. 6649 to Rs. 13099” , Color filter to “Black”,
And then scrape First 100 shoes data you get. The data should include “Brand” of
the shoes , Short Shoe description, price of the shoe.
Please note that applying the filter and scraping the data , everything should be
done through code only and there should not be any manual step.

In [43]:
driver=webdriver.Chrome()
url='https://www.myntra.com/shoes'
driver.get(url)


pricefilter=driver.find_element_by_xpath('//input[@class="price-input"]')
#pricefilter=driver.find_element_by_css_selector('input.value="6687.0 TO 13125.0"')
pricefilter.click()

colorfilter=driver.find_element_by_xpath('//span[@data-colorhex="black"]')
colorfilter.click()

ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=91.0.4472.114)

Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.
You have to scrape 4 attributes of each sneaker :
1. Brand
2. Product Description
3. Price
4. discount %

In [55]:
driver=webdriver.Chrome()
url='https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off'
driver.get(url)
for i in range(3):
    brands=[]
    brand=driver.find_elements_by_xpath('//div[@class="_2WkVRV"]')
    for br in brand:
        brands.append(br.text)
    descriptions=[]
    description=driver.find_elements_by_xpath('//a[@class="IRpwTa"]')
    for desc in description:
        descriptions.append(desc.text)
        
    prices=[]
    price=driver.find_elements_by_xpath('//div[@class="_30jeq3"]')
    for pri in price:
        prices.append(pri.text)
        
    discounts=[]
    discount=driver.find_elements_by_xpath('//div[@class="_3Ay6Sb"]/span')
    for disc in discount:
        discounts.append(disc.text)
    nextbutton=driver.find_element_by_xpath('//a[@class="_1LKTO3"]')
    nextbutton.click()

StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=91.0.4472.114)

In [ ]:
driver=webdriver.Chrome()
url='https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off'
driver.get(url)
for i in range(5):
    try:
        brands=[]
        brand=driver.find_elements_by_xpath('//div[@class="_2WkVRV"]')
        for br in brand:
            brands.append(br.text)
            
        descriptions=[]
        description=driver.find_elements_by_xpath('//a[@class="IRpwTa"]')
        for desc in description:
            descriptions.append(desc.text)
            
        prices=[]
        price=driver.find_elements_by_xpath('//div[@class="_30jeq3"]')
        for pri in price:
            prices.append(pri.text)
            
        discounts=[]
        discount=driver.find_elements_by_xpath('//div[@class="_3Ay6Sb"]/span')
        for disc in discount:
            discounts.append(disc.text)
            
        
    except StaleElementReferenceException:
        pass
    nextbutton=driver.find_element_by_xpath('//a[@class="_1LKTO3"]')
    nextbutton.click()